# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 06:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(default='first', max_length=25)),
                ('l_name', models.CharField(default='last', max_length=25)),
                ('bio', models.CharField(default='bio', max_length=220)),
                ('street', models.CharField(default='street address', max_length=200)),
                ('city', models.CharField(default='city', max_length=100)),
                ('state', localflavor.us.models.USStateField(default='CA', max_length=2)),
                ('zip_code', localflavor.us.models.USZipCodeField(default=12345, max_length=10)),
                ('phone', localflavor.us.models.PhoneNumberField(default=0, max_length=20)),
                ('dob', models.DateField(default='1950-01-01')),
                ('gender', models.CharField(default='Other', max_length=5)),
                ('lob', models.CharField(default='occupation', max_length=40)),
                ('dba', models.CharField(default='comapny', max_length=40)),
                ('synapse_id', models.CharField(default='123456789', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
