# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 05:56
from __future__ import unicode_literals

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=localflavor.us.models.PhoneNumberField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=localflavor.us.models.USStateField(default='CA', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=localflavor.us.models.USZipCodeField(default=12345, max_length=10),
        ),
    ]
