# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 23:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_bundle_expense_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_friend_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=150, null=True)),
                ('description', models.CharField(default='some action', max_length=200)),
                ('reference', models.IntegerField(default='101', null=True)),
                ('status', models.SmallIntegerField(default=1)),
                ('accepted', models.SmallIntegerField(default=1)),
                ('validation', models.SmallIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
