# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useractivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='validation',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='category',
            field=models.IntegerField(default=1),
        ),
    ]
