# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171122_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business',
            field=models.CharField(default='INDIVIDUAL', max_length=20),
        ),
    ]
