# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Request'),
        ),
    ]
