# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 02:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('description', models.CharField(default='expense', max_length=200)),
                ('name', models.CharField(default='expense', max_length=100)),
                ('location', models.CharField(default='location', max_length=100)),
                ('status', models.SmallIntegerField(default=1)),
                ('reference', models.IntegerField(default='101', null=True)),
                ('created_by', models.CharField(default='username', max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
