# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groupactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupactivity',
            name='reference',
            field=models.IntegerField(default=0),
        ),
    ]
