# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_groupactivity_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='location',
        ),
    ]
