# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 00:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SynapseAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Bank Account', max_length=100)),
                ('account_id', models.CharField(default='00000', max_length=100)),
                ('account_class', models.CharField(default='Checking', max_length=50)),
                ('bank_name', models.CharField(default='DefaultBank', max_length=150)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('main', models.IntegerField(default=1)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
